### ISSUE TITLE
rename the repo

### ISSUE THREAD

**Issue by das-g** [geometalab/awesome-apis-for-crowdsourced-data#1]
The aim of this repository is to build a commented list of links to APIs that can be used to query (or even contribute to / edit / modify / add) content on [OpenStreetMap](https://www.openstreetmap.org/), [Wikipedia](https://www.wikipedia.org/), [Wikimedia Commons](https://commons.wikimedia.org) and [Wikidata](https://www.wikidata.org/).

The current repo name `awesome-data` is rather too general to communicate that.

- [ ] think of a more descriptive but still catchy name
- [ ] rename the repository

**Comment by das-g** [comment]
The name `awesome-crowdsourced-data-apis` was suggested, but I think it's too ambiguous: Does it mean "data APIs" that are "crowdsourced" or (as it should) "APIs" for "croudsourced data"?

**Comment by das-g** [comment]
I thought of the name `awesome-vgi-apis` (VGI being short for "volunteered geographic information", the academic(?) term for crowdsourced geodata), but only OSM is limited to geographic data, the other projects in scope also hold other data that APIs of interest might expose.

**Comment by sfkeller** [comment]
VGI seems questionable: http://blog.imagico.de/wissenschaft-und-openstreetmap-und-warum-man-es-nicht-vgi-nennen-sollte/ . Can't see a problem with ambiguosity (what is crowdsourced data APIs anyway?), so still `awesome-crowdsourced-data-apis`.

 .

**Comment by sfkeller** [comment]
There are options nevertheless:

- awesome-apis-for-osm-wikidata-wikipedia-commons
- ...

**Comment by das-g** [comment]
I've renamed the repo to `awesome-apis-for-crowdsourced-data` for now. Not as catchy as one would wish, but more descriptive than `awesome-data`.
